"""
A configuration file for setting desired input parameters to generate a number of .dnd files.
Values can be set as a fixed number or a list of [start, stop, step].
The .dnd files containing every possible combination can be generated by running
'Generate_dnd_template_and_files_from_config_py.py'.
"""

from datetime import date

# set values for some parameters
config = {
    "__Latitude": 52.4000,  # Latitude of Amsterdam
    "__Air_NH3_concentration": 0.06,  # default
    "__Air_CO2_concentration": [
        300,
        1300,
        200,
    ],  # Default CO2 in air is 350. In greenhouse, for most crops, saturation point is 1000-1300 ppm
    # "__pH": 6.5,  # a reasonable soil pH for tomatoes
    # "__Soil_salinity": 0,  # default
    # "______Water_amount": [0.1],  # the water amount(cm) in each day irrigation
    # "______Crop_ID": 45,  # Crop: tomato (this is not changeable, only for reference)
    # "______Planting_month": 3,
    # "______Planting_day": 1,
    # "______Harvest_month": 8,
    # "______Harvest_day": 1,
}

# set irrigation dates (irrigate every day within the date range)
start_date = date(2023, 3, 1)
end_date = date(2023, 8, 1)  # by default use the same period as planting period
